# Generated by Django 3.1.2 on 2020-11-02 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0002_auto_20201101_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
